# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Plant2Win' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Plant2Win

    pod 'Alamofire'

  target 'Plant2WinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Plant2WinUITests' do
    # Pods for testing
  end

end
